### ISSUE TITLE
Include a license & question about featuring your theme

### ISSUE THREAD

**Issue by rnd195** [rainbowflesh/Rose-Pine-For-Marp#1]
Hi, 

I am building a community-maintained theme gallery for Marp [here on GitHub](https://github.com/rnd195/marp-community-themes), and I'd like to feature your theme. Before that, however, I wanted to reach out to ask **whether you could include a license in your repository.** The original Rosé Pine repository contains an [MIT License](https://github.com/rose-pine/rose-pine-theme/blob/main/license), for your information. [Here's](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) also a very good article from GitHub about licensing repositories.

To get a sense of how I would like to feature your theme, please, take a look at one of the currently hosted themes (e.g., [border](https://rnd195.github.io/marp-community-themes/theme/border.html)).

Many thanks.

Martin

**Comment by rainbowflesh** [comment]
Yes! yes and of course feel free to collect, use, and distribute! I just make mistake for a long time for forgot add a license! 

Here the [MIT](https://github.com/rainbowflesh/Rose-Pine-For-Marp/blob/master/license) ;)

**Comment by rnd195** [comment]
Wonderful, thank you very much!

Closing the issue.
